### ISSUE TITLE
Add support for .tga image viewing

### ISSUE THREAD

**Issue by NessieHax** [PhoenixARC/-PCK-Studio#3]
`The Nightmare Before Christmas` has some images as .tga files stored

**Comment by yaboiFoxx** [comment]
Sorry for being late, I haven't worked on this project! But I'm not a coder much myself. I need to update my program to the latest version of PCK Studio so that it has all latest features of PCK Studio. There are a lot of problems with this program, but I'm trying my best to fix them! Once its updated to the new version of PCK Studio, this will be fixed. I think, lol.

**Comment by NessieHax** [comment]
Added in commit f645914ee6c29dc74f38b1a0548439363eb609f7
